### ISSUE TITLE
Struct _Object_type

### ISSUE THREAD

**Issue by maskelihileci** [horsicq/xntsv#2]
Hello, I will add a new struct, I do not understand what the area I marked

![RkrRn RlıRtısı](https://user-images.githubusercontent.com/41159853/84570754-2c6a0000-ad98-11ea-81ed-90eceb4d9d15.PNG)

2. https://www.vergiliusproject.com/kernels/x64/Windows%2010%20%7C%202016/1703%20Redstone%202%20(Creators%20Update)

Isn't there a way to add the data here more easily to the program ?

**Comment by horsicq** [comment]
Hello! Thanks a lot for the bugreport. I will think about it.

**Comment by maskelihileci** [comment]
I was wondering, did you add all the structs one by one? Or is there an easy way to do this?

I want to add current structures, do I have to deal with them one by one?

**Comment by horsicq** [comment]
Thanks for your idea. I will make a tool to add new struct easily.
