### ISSUE TITLE
oh my friend

### ISSUE THREAD

**Issue by maskelihileci** [horsicq/xntsv#5]
Dude, if signing a driver is a problem, I could handle it.
There are also methods to disable signature checks. I wish you hadn't given up on the old project.

We also took the promise of adjusting the structs according to the current systems. Anyway, good luck

**Comment by horsicq** [comment]
Thanks a lot!

**Comment by horsicq** [comment]
The next version of XNTSV will be with driver again. :)

**Comment by maskelihileci** [comment]
I am very happy thank you

I want to ask one more thing, are you not showing some applications in the process list on purpose?

system PID : 04
smss.exe PID : 444
crss.exe PID : 632
wininit.exe PID : 716
csrss.exe PID : 724
services.exe PID : 788

These are not listed.

**Comment by horsicq** [comment]
Do you use 64 bit version "run as admin"?

**Comment by maskelihileci** [comment]
Yes I'm starting as administrator, Signed in driver
xntsv 2.01 , xntsv 2.00  There was no such problem in versions
I wonder if you changed the algorithm you used to list the processes.

**Comment by horsicq** [comment]
Thanks. I will take a look.

**Comment by horsicq** [comment]
Fixed.
