### ISSUE TITLE
Sign driver

### ISSUE THREAD

**Issue by npo6ka** [horsicq/xntsv#9]
I'm not good with driver signatures, so I wanted to clarify how to install a signed driver.
When I first started the program, I got an error installing the driver. I created a test certificate, but how do I install the driver now? What is it called?
When starting the program, it just displays the error "Cannot load driver"

**Comment by horsicq** [comment]
//  I created a test certificate

You have to disable some things on your PC: https://github.com/horsicq/build_tools/blob/52ab4c770511ad3d4bf13ea56da79f40b4d5475e/WINDOWS_DISABLE_DRIVER_SIGNATURE.md

**Comment by npo6ka** [comment]
I turned it off, what should I do next? How to install the driver?

**Comment by horsicq** [comment]
You do not need install just sign xwiniodriver.sys with test cert

**Comment by npo6ka** [comment]
Everything worked out! Thank you!
